src/pages/wallets/wallets.html, src/pages/wallets/wallets.ts
=> hidden btn Scan WalletsPage

src/components/info-sheet/info-sheet.html, src/pages/add/select-currency/select-currency.ts, src/providers/currency/token.ts
-fix Displaying a message to select eth for ducx tokens
-fix Show ducx wallet for eth tokens
-Removed the ability to select a token to bind to a token
-fix Already linked ducx wallets were displayed
Убрал тернарник
=> fix ShowWallets for linking tokens

src/pages/calculator/calculator-convert/calculator-convert.ts
now if there are no wallets with a suitable amount. showing an error window
Добавил функцию которая выводит окно с сообщением, если кошельков с необходимой суммой нет у пользователя
=> add  modal SwapPage

src/pages/calculator/calculator-convert/calculator-convert.ts
fix autosubstitution send Address
=> fix swapPage

src/pages/send/amount/amount.ts
Dr-13 DR-124
Теперь подставляем balanceSTR, вместо balanceSat
У себя потестил. Вроде работает, но может где-то что-то сломаться. 
Не тестил для баланса больше 100.
=> Fix send max

package.json, src/pages/deposit/deposit.html, src/pages/deposit/deposit.scss, src/pages/deposit/deposit.ts
-Alternative balance display DepositPage
=> add Alternative balance || DepositPage

src/pages/send/amount/amount.ts
-now you can not put more than 1 point 
DR-127
=> Fix amount formatting | AmountPage

src/pages/pages.ts, src/pages/settings/feedback/feedback.html, src/pages/settings/feedback/feedback.scss, src/pages/settings/feedback/feedback.ts, src/pages/settings/settings.html, src/pages/settings/settings.ts
Добавил страницу обратной связи
=> add feedBackPage

src/pages/send/send.ts, src/providers/incoming-data/incoming-data.ts
Добавил для ducx проверку URI.
=> upd Qr-code | SendPage

src/pages/calculator/calculator.html
=> upd validate AmountForm | SWAP

src/pages/tx-details/tx-details.scss
1. исправлена верстка
https://manzoni.atlassian.net/browse/DR-196?focusedCommentId=12869&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12869
=> fix styles

package.json, src/components/choose-fee-level/choose-fee-level.scss, src/components/wallet-item-content/wallet-item-content.html, src/components/wallet-item-content/wallet-item-content.scss, src/components/wallet-item-content/wallet-item-content.ts, src/pages/calculator/calculator-convert/calculator-convert.ts, src/pages/calculator/calculator.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts
1. Исправление кнопки опций в кошельке https://manzoni.atlassian.net/jira/software/projects/DR/boards/82?assignee=618e316ef1ff560069e772f0&selectedIssue=DR-217
2. Исправление верстки баланса в выпадающем меню https://manzoni.atlassian.net/jira/software/projects/DR/boards/82?assignee=618e316ef1ff560069e772f0&selectedIssue=DR-169
=> Bug fix/fix more option button on tokens

package.json, src/components/choose-fee-level/choose-fee-level.scss, src/components/wallet-item-content/wallet-item-content.html, src/components/wallet-item-content/wallet-item-content.scss, src/components/wallet-item-content/wallet-item-content.ts, src/pages/calculator/calculator-convert/calculator-convert.ts, src/pages/calculator/calculator.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts
Reverts DUCATUS-revival/ducatus-copay#69
=> Revert "Bug fix/fix more option button on tokens"

src/pages/tx-details/tx-details.scss
Reverts DUCATUS-revival/ducatus-copay#70
=> Revert "fix styles"

.vscode/settings.json, src/components/info-sheet/info-sheet.html, src/pages/calculator/calculator.ts, src/providers/action-sheet/action-sheet.ts
if you select WDUCX SWAP then wen show alert
=> add AlertWarning | CalculatorPage

src/components/wallet-receive/wallet-receive.html, src/components/wallet-receive/wallet-receive.scss
=> fix designBugs | walletReceivePage

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts
=> fix bugs | ChooseFeeLevel

src/pages/calculator/calculator-convert/calculator-convert.ts
Если нет тестовых кошельков для получения, то показываем модалку с ошибкой
=> upd CalculatorPage

src/components/exchange-rates/exchange-rates.ts, src/providers/currency/currency.ts
Захардкодил, цену USDC потому что там делается запрос  https://ducws.rocknblock.io/bws/api/v2/fiatrates/USD
и возвращаются там только те, что сейчас на домашней страницы
=> add USDC | HomePage

src/pages/calculator/calculator-convert/calculator-convert.ts, src/pages/calculator/calculator.html, src/pages/calculator/calculator.ts
Высчитываем сумму для получения, для 1 отправленной монеты. и отображаем
=> fix viewRates

src/pages/voucher/add/add.ts
=> fix VoucherPage

src/pages/voucher/add/add.ts
Reverts DUCATUS-revival/ducatus-copay#114
=> Revert "fix VoucherPage"

src/pages/send/amount/amount.ts
При отправке send Max в amount Module Выводятся ненужные нули. 
Обрезаю полученные нули путем преобразования в Number() amount.ts 
Добавил типы для переменных и функций 
Переписал функцию evalute
Там зачем-то использовался eval(), который потенциально дыра в безопасности. Заменил его на Number()
=> upd-fix amountPage SendMax

src/pages/deposit/deposit-add/deposit-add.ts, src/pages/deposit/deposit.html, src/pages/deposit/deposit.ts
Задача 
Получить информацию о ставки по депозитам и отображать ее.
Делаю запрос. Умножаю значения процентных ставок на 100. Т.к они представлены в виде 0.08 
Антон добавил поле. interestRate в информацию о сделанных депозитах. И теперь я просто ее отображаю, а не обращаюсь к таблицы месяц-ставка
=> added getting information about deposit rates

src/pages/deposit/deposit.scss
Кнопочки выбора вертикально не по центру были
Теперь по центру
=> style bugs fixed

src/pages/deposit/deposit.scss
Добавил нижний отступ для кнопочки
=> added bottom margin for the button | deposit page

src/pages/deposit/deposit-add/deposit-add.html, src/pages/deposit/deposit-add/deposit-add.ts
Были жестко прописаны значения процентной ставки в шаблоне 
Поправил. Теперь получаем значения из компонента
=> adding dynamic interest rate retrieval

src/components/wallet-item-content/wallet-item-content.scss
Добавил мин ширину, чтоб альт баланс в 1 строку был
=> added min width for balance

src/pages/send/amount/amount.ts
Проблема. Нет ограничения на decimals на странице amount. Птм она обрезается и отправляемая сумма не совпадает с той, которую ввели
Решение. Обрезаем отправляемую сумму, если она превышает decimals
=> added truncation of the amount to decimal places of the coin

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts
Не копировался и не показывался адрес при нажатии на sendingFrom
Получил адрес. И вместо функции воспользовался директивой copy-to-clickBoard.
=> added addressFrom copy-to-clickboard | ConfirmPage

src/pages/swap/swap.html, src/pages/swap/swap.scss, src/pages/swap/swap.ts
Reverts DucatusX/ducatus-copay#168
=> Revert "Revert "Fix swap history in swap page.""

src/pages/freeze/freeze-add/freeze-add.ts, src/providers/wallet/wallet.ts
Раньше отправляли WalletID отправителя. Теперь получателя
=> changed walletID in request body

src/pages/deposit/deposit.html, src/pages/deposit/deposit.scss, src/pages/deposit/deposit.ts
Проблема на одной кнопки было 2 вызова апишки вывод дивидендов и депозита.
И бывало так что вывод дивидендов отрабатывался, а депозита нет(интернет плохой например)
И при повторном вызове вывод дивидендов возвращал ошибку и вывод депозита не срабатывал потому что выполнение программы переходило в блок Catch 
Решение 
Если депозит новый, то там будет одна кнопка - Withdraw
Если старый, то там будет 2 кнопки - Withdraw и Get Rewards
Withdraw выводит депозит, а get Rewards - дивиденды
=> feat: added buttons for withdrawing old deposits

src/pages/add/select-currency/select-currency.ts
=> feat: AA+ default token when creating a wallet
